### ISSUE TITLE
Getting answer

### ISSUE THREAD

**Issue by Pamela281** [JAQuent/functions-for-matlab#4] opened 2021-05-20 14:31 UTC
Hi Jörn, 

I actually using your slide scale as a visual analog scale for my experiment. I have two questions : 
 - Is it possible to have two slide scale with different questions above them on the same screen ? (I don't know if it's clear)
 - How can I fetch participants answer and implement it on a txt file ? 

Thanks a lot, 
Pamela

**Comment by JAQuent** [comment] 2021-05-23 13:31
Hi Pamela,
That's cool that you're using this. 
To your first question, it is in principle adapt the code for have two scales one screen, which could be controlled by two sets of keys. 

To your second question, I am unsure what you mean. However, it is relatively easy to save the data from PTB experiment as a .csv (or other text file). An example from me can be found here: https://github.com/JAQuent/nBack/blob/master/nBack.m. This is fairly independent from the slide scale though. 

I hope that helped a bit.

**Comment by Pamela281** [comment] 2021-07-13 12:49
Hi Jörn, 

Thanks a lot ! 
I have another question : I don't understand why whether I put 'center' or 'left', the slider doesn't change its position on the scale, and moreover when I increase the length of the scale, the slider doesn't go to the left, nor to the right, nor to the center. 

Do you know why ?

**Comment by JAQuent** [comment] 2021-07-14 10:08
Hey,

I just wanted to let you know that I probably won't have time to deal with in the next two weeks.

In case, you still need help I'll try to do my best.

For that it would be useful to see some code.

Best wishes,
Alex 

On 13 July 2021 14:49:30 CEST, Pamela281 ***@***.***> wrote:
>Hi Jörn, >
>>
>Thanks a lot ! >
>I have another question : I don't understand why whether I put 'center'
>or 'left', the slider doesn't change its position on the scale, and
>moreover when I increase the length of the scale, the slider doesn't go
>to the left, nor to the right, nor to the center. >
>>
>Do you know why ? >
>>
>-- >
>You are receiving this because you commented.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/JAQuent/functions-for-matlab/issues/4#issuecomment-879058349

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Pamela281** [comment] 2021-09-07 13:44
Hi, 

Sorry, I was in holidays, so I didn't have time to deal with programmation issues. However, here is some code for you that can be useful: 

`
KbName('UnifyKeyNames');

center        = round([rect(3) rect(4)]/2);
lineLength    = 10;
width         = 3;
scalaLength   = 0.9; %modifié (default : 0.9)
scalaPosition = 0.6;
sliderColor   = [255 0 0];
scaleColor    = [0 0 0];
device        = 'keyboard'; % default : mouse
aborttime     = 10 ; %temps en sec pour donner une réponse (default : Inf)
responseKeys  = [KbName('y') KbName('g') KbName('b')]; %j = index, k = majeur, h = pouce
GetMouseIndices;
drawImage     = 0;
startPosition = 'right'; % position slider
displayPos    = true; %the position of the slider is displayed (default : false)
rangeType     = 2; % the range is from 0 to 100 (default : 1)
stepSize      = 10; %vitesse de déplacement du curseur (default : 1)

if strcmp(startPosition, 'right')
    x = globalRect(3)*scalaLength;
elseif strcmp(startPosition, 'center')
    x = globalRect(3)/3;
elseif strcmp(startPosition, 'left')
    x = globalRect(3)*(1-scalaLength);
else
    error('Only right, center and left are possible start positions');
end

`

Best wishes, 
Pam

**Comment by Pamela281** [comment] 2021-09-07 15:06
Hey, 

Another question : why globalRect and rect are different ? (see photo)

![image](https://user-images.githubusercontent.com/60964329/132367963-9e362260-d571-4127-874a-7b27179cac4f.png)

Thanks a lot for your help, 
Pam

**Comment by Pamela281** [comment] 2021-09-08 09:42
Hey ! 

I managed to put the slider in the middle of the scale by changing `x = globalRect(3)/2;` by `x = center(1); `

Best wishes, 
Pam

**Comment by JAQuent** [comment] 2021-09-13 07:33
Hey Pamela, 
Is this an issue with my code or your code? I've played around with slide scale and I can change the start position and the scale length as intended (see new test script). 

If you can't use my code as intended, could you send me a short script that highlights the problem?

I am happy to help in any case but I could close the issue if it is not related to the code itself.

**Closed as completed** 2022-10-16 11:53 UTC
